$(function(){
	//
	$(".p1").hover(function(){
		$(".pindao").show();
	},function(){
		$(".pindao").hide();
	})
	//
	$("#s-1").focus(function(){
		$(this).val("")
		$(".h7").show();
	})
	$("#s-1").blur(function(){
		$(this).val("无心法师2")
		$(".h7").hide();
	})
	//
	$(".l1").hover(function(){
		$(this).children("img").attr("src","img/watch_d_now.png");
		$(this).children(".small").css("color","wheat")
	},function(){
		$(this).children("img").attr("src","img/icon-看过-黑-hover.png");
		$(this).children(".small").css("color","")
	})
	$(".l2").hover(function(){
		$(this).children("img").attr("src","img/up_d_now.png");
		$(this).children(".small").css("color","wheat")
	},function(){
		$(this).children("img").attr("src","img/icon-上传-黑-hover.png");
		$(this).children(".small").css("color","")
	})
	$(".l3").hover(function(){
		$(this).children("img").attr("src","img/kh_d_now.png");
		$(this).children(".small").css("color","wheat")
	},function(){
		$(this).children("img").attr("src","img/kh_d_hover.png");
		$(this).children(".small").css("color","")
	})
	//
	$(".l1").hover(function(){
		$(".kanguo").show();
	},function(){
		$(".kanguo").hide();
	})
	$(".l3").hover(function(){
		$(".kehuduab").show();
	},function(){
		$(".kehuduab").hide();
	})
	$(".h6").hover(function(){
		$(".denglv").show();
	},function(){
		$(".denglv").hide();
	})
//	右边固定到货
   $(".zbgd>.er4>div>.x").click(function(){
   	$(".zbgd>.er4").hide();
   })
   $(".zbgd>.y").click(function(){
   		$(".zbgd>.er4").show();
   })
	$(".zbgd>.er4>div").hover(function(){
		$(this).css("background","#EEEEEE")
	},function(){
		$(this).css("background","white")
	})
})



